### ISSUE TITLE
Token TRC PK ownership

### ISSUE THREAD

**Issue by 30mb1** [Open-Everscale/TIPs#2]
It is necessary to decide whether it is required to implement the public key management feature in the token wallet

Against:
 - Smart-contract code is much bigger, it leads to increased storage fees
 - User should maintain balance of every token wallet separately

For:
 - No additional internal message from ton wallet to token wallet. It means no additional fwd fee

It is obviously that main use case for token wallet is extension like metamask or some kind wallet. Should we keep this functionality for <1% of users? It is better to include it in some extension.

Need to clarify this to for [TRC token standard ] - #1

Send +1 if you are for REMOVING PK from standard, -1 otherwise or share your opinion and we will discuss it

**Comment by 30mb1** [comment]
+1

**Comment by aleksandr-hramcov** [comment]
+1

**Comment by 30mb1** [comment]
Комментариев против не поступило, считаем, что все согласны.
